### ISSUE TITLE
Packaging issue with 2.2.5.1 on PowerShell Gallery

### ISSUE THREAD

**Issue by Jon007** [EliteLoser/DotNetVersionLister#1]
There seems to be an issue with the latest release on powershellgallery.com
https://www.powershellgallery.com/packages/DotNetVersionLister/2.2.5.1

the Get-DotNetVersion is not exported by 2.2.5.1, is only exported by previous version:

```
Update-Module -Name DotNetVersionLister;
Get-Module;

ModuleType Version Name ExportedCommands
---------- ------- ---- ----------------
Manifest 2.2.5.1 DotNetVersionLister
Script 2.2.4 DotNetVersionLister Get-DotNetVersion
```

On a first time install using powershellgallery as source:
```
Install-Module -Name DotNetVersionLister
Get-DotNetVersion -LocalHost
Get-DotNetVersion : The term 'Get-DotNetVersion' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1

```

It is of course possible to download the psm1 file, import it and it works as expected:
```
Import-Module c:\DotNetVersionLister.psm1
Get-DotNetVersion -LocalHost
```
etc.. works fine.

**Comment by EliteLoser** [comment]
Terrible sorry about that.
Tested with an old 2.2.3 version that had snuck into my profile on the test box, apparently.
Should be fixed in 2.2.5.2 in the Gallery and here on GitHub now.

Tested this way:
```
PS C:\> Install-Module -Name DotNetVersionLister -Force
PS C:\> Import-Module DotNetVersionLister
PS C:\> (Get-Module DotNetVersionLister).Version

Major  Minor  Build  Revision
-----  -----  -----  --------
2      2      5      2


PS C:\> Get-DotNetVersion -LocalHost


ComputerName : localhost
>=4.x        : 4.6.2
v4\Client    : Installed
v4\Full      : Installed
v3.5         : Not installed (no key)
v3.0         : Not installed (no key)
v2.0.50727   : Not installed (no key)
v1.1.4322    : Not installed (no key)
Ping         : True
Error        :
```

And I get 4.7.2 as .NET version on my Win 10 Home box, so that version support "works".
Here is the PowerShell Gallery link of the "commit" that fixes: https://www.powershellgallery.com/packages/DotNetVersionLister/2.2.5.2

Fixed in this commit on GitHub: https://github.com/EliteLoser/DotNetVersionLister/commit/838c7aa17ce838758cb0fe71ca638de493051dae
