### ISSUE TITLE
dotNet version 5 or higher reporting on

### ISSUE THREAD

**Issue by animatco** [EliteLoser/DotNetVersionLister#20]
I know this is an older module for you, but have you figured out a way to tell if dotNET 5, 6, 7 or the latest version dotNET 8 is installed?

**Comment by EliteLoser** [comment]
Hi. I spent 2-3 hours writing something simple that could help beginners out a bit. I feel like it's kind of poor quality and "anyone could have done this", but there it is. Have a look at Get-STDotNetVersion2.ps1 here, you can dot-source it and get a function that takes care of the basic parsing into objects, etc... https://github.com/EliteLoser/DotNetVersionLister/tree/master/5AndUp 

Let me know if you need help using it or have suggestions on what I should add to the brief docs..

**Comment by EliteLoser** [comment]
I started to implement it and had to fix some bugs (not yet committed to the new branch).

However, it's so slow that I'll definitely make it non-default behavior, if I at all support it in my code.

After 15 minutes of searching through C: (I implemented it so you can pass an array of drives to search - default C: and D:), I gave up waiting and aborted... I think most needs are covered by being able to pass in the path to dotnet.exe. Searching is done "locally on the remote computer, so it's faster than over the network via a UNC path (\\computer\x$), but Get-ChildItem is known to be potentially slow.

I'm thinking people can inventory other locations for dotnet.exe and handle those separately. Not sure, but it's too slow with Get-ChildItem. I know robocopy.exe can be used to list files fast, but that seems hairy to involve in the process. Also some .NET methods (where you have to handle recursion yourself), but they are not fast enough either.

By the way, your code, using $Env:ComputerName, would search your local computer, using a UNC path. You meant to use the current foreach loop's `$ComputerName`.

Tip: To insert code, use three backticks, press enter, handle possible quirks, add code, and end with three backticks on a single line again - and it will show up as a code block.

**Comment by animatco** [comment]
You are correct about the $Env:Computername, I had replaced the actual server I had used as test case for finding the actual path. In the environment I am working in, at least for me the search was pretty quick. I had not thought about what if on a different volume. If having to test if A: thru Z: exists that would defiantly add time.

**Comment by Suncatcher** [comment]
So was it ever implemented? Does it shows .Net Core 6,7,8 if they are installed?

**Comment by EliteLoser** [comment]
As you are now inadvertently pointing out, the best user experience would be one product/command/function for all collection of both .NET Framework and Core versions. It's a tiny bit complicated, or inconvenient, how it would have to present the results given the vastly different characteristics of the data to present.

For now, as you could have seen from the link in an earlier comment ( https://github.com/EliteLoser/DotNetVersionLister/tree/master/5AndUp ), it's in a separate function.

See the help for an example of how to download and import/load the script, collect versions and handle the logic. NB. There is no local host version detection, only remote, in that function.

It's not as polished as the version for the .NET framework, but covers 90 + percent of needs.

**Comment by Suncatcher** [comment]
> It's a tiny bit complicated, or inconvenient, how it would have to present the results given the vastly different characteristics of the data to present.

Well, everything is possible, it's a matter of choice how to present it.

> NB. There is no local host version detection, only remote, in that function.

then this script is almost useless. The 90% of the cases is when you need to do it it on localhost. The remote .NET analysis that requires WinRM-enabled machines is purely admin tool, and admins usually know how to handle this task by themselves

**Comment by EliteLoser** [comment]
I have gone over my response several times and removed the anger, and will refrain from ad hominem, however tempting initially. Short fuse.

If these admins knew how to do it themselves, they would not google my script. Most IT specialists google almost everything they do, certainly something as complex as this. Do you think end users google (or bing) how to check .NET versions with PowerShell? Who do you think will use this? I am probably wasting time and energy and maybe being trolled. :'( If the admins knew how to do it, they wouldn't seek out methods on the web (and they do). You would be surprised what some "admins" know and don't know..

If the script is useless, you are free to not use it. If you were an admin, then, per your own words, you would perhaps take how I handle the slightly (to me - for some very) complex part with regex parsing and paste it into your console. The rest is for the imagined  95% of cases where admins are reporting versions. PowerShell users are, in general, "admins" or developers. And even the average developer is likely to google how to do this task, btw.

WinRM is enabled in most sane shops.

Look at the code and take the relevant parts, then. If all you want is a "local host detection" for one server or workstation then why do you even need PowerShell... Maybe to produce a standardized inventory report by running it locally, but... Is that common, uh... A bad end to my evening with this somewhat ignorant and ungrateful attitude here. ;-(

I know it's possible, I even outlined how you can do it with a quite brilliant script I wrote (Jeffrey Snover, inventor of PowerShell, tweeted me kudos about it). Merge-Csv, a function that, with the -AllowDuplicates parameter, would do precisely a presentation of the versions "cascading down" with less data on the later entries. I don't expect you to fully understand this, so don't worry about your current confusion. Anyway... I could make it so "DotNetVersionLister" (currently only for the .NET Framework) had, for instance, two more properties of arrays of objects with the results currently in my second "Get-STDotNetVersion2" function (that can easily be adapted by any PowerShell developer worth his salt, although not most admins...). One property for SDKs, one for Runtimes. Maybe I will do it.

You demonstrated that you seemingly don't read even the thread you post in (the link in plain sight in this issue was ignored, then you come back and attack my code, efforts and reasoning), but if you had been more observant, you would have seen the examples (and code). This (directly, unaltered) pasted code from my function will do the local host .NET SDK and Runtime to PowerShell object part. I am somewhat confused about why you need this on a LOCAL HOST - and claim this is the 90+% of cases? Then you can just view the output from the commands directly, why do you even want PowerShell objects, then... This is for automation, inventory and reporting. This is quite weird... I don't get it... what's the scenario? You could "deploy" the script and run it locally, I can imagine a need for that in some cases (but not the majority) such as running Ansible inventorying, or something like that.

Idk. I agree that it would be better to have it all in one function, but the sour attitude is depressing. I'll probably make a version of the .NET 5+ code where I add functionality also for the local host, based on this feedback, so thanks anyway.

You will obviously need to define the variable with the path to dotnet.exe before you run it, but this will do what you ask (and was pasted directly from the script):

```
if (-not (Test-Path -LiteralPath $DotNetExePath -PathType Leaf)) {
                Write-Warning "[$Env:ComputerName] Path to dotnet.exe doesn't exist ($DotNetExePath). Cannot continue with this computer."
                return
            }
            # SDK section.
            try {
                foreach ($SDK in & $DotNetExePath --list-sdks) {
                    if ($SDK -match '^(?<Version>[\d.]+)\s+\[(?<Path>.+)\]\s*$') {
                        # Not [PSCustomObject] for PSv2 compatibility...
                        New-Object -TypeName PSObject -Property @{
                            ComputerName = $Env:ComputerName
                            SDKVersion = $Matches['Version']
                            SDKPath = $Matches['Path']
                        } | Select-Object -Property ComputerName, SDKVersion, SDKPath, RuntimeType, RuntimeVersion, RuntimePath
                        # The Select-Object above is for PSv2 quirks mode to include all properties for all objects.
                    }
                    else {
                        Write-Warning "[$Env:ComputerName] Unrecognized output from 'dotnet.exe --list-sdks'. Output was '$SDK'."
                    }
                }
            
            }
            catch {
                Write-Warning "[$Env:ComputerName] Failed to execute 'dotnet.exe --list-sdks'. Error was '$_'"
            }
            # Runtime section.
            try {
                foreach ($Runtime in & $DotNetExePath --list-runtimes) {
                    if ($Runtime -match '^(?<RuntimeType>\S+)\s+(?<Version>[\d.]+)\s+\[(?<Path>.+)\]\s*$') {
                        # Not [PSCustomObject] for PSv2 compatibility...
                        New-Object -TypeName PSObject -Property @{
                            ComputerName = $Env:ComputerName
                            RuntimeType = $Matches['RuntimeType']
                            RuntimeVersion = $Matches['Version']
                            RuntimePath = $Matches['Path']
                        } | Select-Object -Property ComputerName, SDKVersion, SDKPath, RuntimeType, RuntimeVersion, RuntimePath
                        # The Select-Object above is for PSv2 quirks mode to include all properties for all objects.
                    }
                    else {
                        Write-Warning "[$Env:ComputerName] Unrecognized output from 'dotnet.exe --list-runtimes'. Output was '$Runtime'."
                    }
                }
            
            }
            catch {
                Write-Warning "[$Env:ComputerName] Failed to execute 'dotnet.exe --list-runtimes'. Error was '$_'"
            }
```

I'm sure I will be attacked again for my now useless answer and of course all admins on Earth know all this (from age 7 and up) and you didn't actually need to hear it and God knows what else... Thanks... ;( I'll go cry myself to sleep now, being so useless.

**Comment by Suncatcher** [comment]
Sorry I didn't want to troll you or smth, but I wanted just to note that making script remote host-only you make it quite limited in nature and cut out many possible use-cases, maybe this number is not 90% but 50% is the minimum. I didn't try to diminish your efforts, by no means, but not only admins are the users of the script and you cut all the rest.

> WinRM is enabled in most sane shops.

I disagree with that. WinRM poses a security risk and this is not my opinion, but the opinion of many ifosec sepcialists:

https://security.stackexchange.com/questions/5951/what-are-the-security-implications-of-enabling-winrm-on-all-domain-members
https://www.eventsentry.com/validationscripts/guid/1c1e3c39-98a3-41cb-8bf1-1a5f36a6c950

There are serious implications of enabling WinRM and strong counter-attack measures that must be taken which Microsoft describes here https://learn.microsoft.com/en-us/powershell/scripting/learn/remoting/winrmsecurity?view=powershell-7.3

When there are options enable or not to enable just for one-time task like checking .NET the choice obviously is **not**.

**Comment by EliteLoser** [comment]
I added local host support (default) in this commit: https://github.com/EliteLoser/DotNetVersionLister/commit/459367f4b14fe3307fcc04d444a113573e49155f

**Comment by EliteLoser** [comment]
By the way, if you're not using WinRM, the world's most-tested version of remote access, except for SSH, you are likely relying on some other "opening" (or how can you get inventory, perform ad hoc tasks?) that can be exploited.

Mostly it makes administration of hacking equally easy and convenient, in some ways, I don't know all about this, but I remember reading that Microsoft actively encourages hacking to be done with PowerShell (could be outdated). Something involving traceability and stuff. It will improve the security, I suppose?

I implemented the localhost version. Doing it was trivial. I can quite easily add this (under the hood using the new function) to DotNetVersionLister. I would, as I said earlier in this thread, present it as two properties of arrays of custom PowerShell objects. It will make full reporting more complex for the users of the code/function, but at least the data will be available, and the user experience significantly better. It's 'cooler', too. Hm.. Yeah, give me a sec.
